import { Heart, Search, Clock3, ArrowRight, ChefHat, Menu, X } from 'lucide-react';
import { Link, NavLink, Route, Routes, useParams } from 'react-router-dom';
import { useMemo, useState } from 'react';
import { recipes } from './data/recipes';
import type { Recipe } from './types/recipe';

function Header() { const [open, setOpen] = useState(false); return <header className="header"><Link to="/" className="logo"><span className="logo-mark"><ChefHat size={22}/></span>Meine Rezepte</Link><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menü öffnen">{open?<X/>:<Menu/>}</button><nav className={open?'nav open':'nav'}>{[['/','Startseite'],['/rezepte','Rezepte'],['/favoriten','Favoriten']].map(([to,label])=><NavLink key={to} to={to} onClick={()=>setOpen(false)}>{label}</NavLink>)}</nav></header> }
function Card({ recipe, favorite, toggle }: { recipe: Recipe; favorite: boolean; toggle: (id:string)=>void }) { return <article className="card"><Link to={`/rezepte/${recipe.id}`}><img src={recipe.image} alt={recipe.title}/></Link><div className="card-body"><div className="card-top"><span className="tag">{recipe.category}</span><button className={favorite?'heart active':'heart'} onClick={()=>toggle(recipe.id)} aria-label="Favorit umschalten"><Heart size={19} fill={favorite?'currentColor':'none'}/></button></div><Link to={`/rezepte/${recipe.id}`}><h3>{recipe.title}</h3></Link><div className="meta"><span><Clock3 size={15}/>{recipe.time}</span><span>{recipe.difficulty}</span></div></div></article> }
function App() { const [favorites,setFavorites]=useState<string[]>([]); const toggle=(id:string)=>setFavorites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]); return <><Header/><main><Routes><Route path="/" element={<Home favorites={favorites} toggle={toggle}/>}/><Route path="/rezepte" element={<Listing favorites={favorites} toggle={toggle}/>}/><Route path="/favoriten" element={<Favorites favorites={favorites} toggle={toggle}/>}/><Route path="/rezepte/:id" element={<Detail favorites={favorites} toggle={toggle}/>}/></Routes></main><footer>Mit Liebe gekocht · Meine Rezepte</footer></> }
function Home({favorites,toggle}:{favorites:string[];toggle:(id:string)=>void}) { return <><section className="hero"><div><span className="eyebrow">DEIN DIGITALER REZEPTORDNER</span><h1>Gutes Essen.<br/><em>Gute Momente.</em></h1><p>Entdecke einfache, köstliche Rezepte für jeden Tag.</p><Link className="button" to="/rezepte">Rezepte entdecken <ArrowRight size={18}/></Link></div><img src={recipes[0].image} alt="Cremige Tomatenpasta"/></section><section className="section"><div className="section-head"><div><span className="eyebrow">INSPIRATION</span><h2>Beliebte Rezepte</h2></div><Link to="/rezepte" className="text-link">Alle ansehen <ArrowRight size={16}/></Link></div><div className="grid">{recipes.slice(0,3).map(r=><Card key={r.id} recipe={r} favorite={favorites.includes(r.id)} toggle={toggle}/>)}</div></section></> }
function Listing({favorites,toggle}:{favorites:string[];toggle:(id:string)=>void}) { const [q,setQ]=useState(''); const filtered=useMemo(()=>recipes.filter(r=>(r.title+' '+r.category).toLowerCase().includes(q.toLowerCase())),[q]); return <section className="section page"><span className="eyebrow">DIE SAMMLUNG</span><h1>Alle Rezepte</h1><div className="search"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nach Rezepten suchen ..."/></div>{filtered.length?<div className="grid">{filtered.map(r=><Card key={r.id} recipe={r} favorite={favorites.includes(r.id)} toggle={toggle}/>)}</div>:<Empty text="Keine Rezepte gefunden."/>}</section> }
function Favorites({favorites,toggle}:{favorites:string[];toggle:(id:string)=>void}) { const list=recipes.filter(r=>favorites.includes(r.id)); return <section className="section page"><span className="eyebrow">DEINE AUSWAHL</span><h1>Favoriten</h1>{list.length?<div className="grid">{list.map(r=><Card key={r.id} recipe={r} favorite toggle={toggle}/>)}</div>:<Empty text="Du hast noch keine Favoriten gespeichert."/>}</section> }
function Empty({text}:{text:string}) { return <div className="empty"><Heart size={30}/><p>{text}</p><Link className="button" to="/rezepte">Rezepte entdecken</Link></div> }
function Detail({favorites,toggle}:{favorites:string[];toggle:(id:string)=>void}) { const {id}=useParams(); const r=recipes.find(x=>x.id===id); if(!r)return <Empty text="Dieses Rezept wurde nicht gefunden."/>; return <section className="detail"><img src={r.image} alt={r.title}/><div className="detail-copy"><span className="tag">{r.category}</span><h1>{r.title}</h1><p>{r.description}</p><div className="meta"><span><Clock3 size={17}/>{r.time}</span><span>{r.difficulty}</span><button className={favorites.includes(r.id)?'heart active':'heart'} onClick={()=>toggle(r.id)} aria-label="Favorit umschalten"><Heart size={20} fill={favorites.includes(r.id)?'currentColor':'none'}/></button></div><h2>Zutaten</h2><ul>{r.ingredients.map(i=><li key={i}>{i}</li>)}</ul><h2>Zubereitung</h2><ol>{r.steps.map(s=><li key={s}>{s}</li>)}</ol></div></section> }
export default App;
